POST https://localhost:5001/api/users/auth
Content-Type: application/json

{
  "email": "webmasterdevlin@gmail.com",
  "password": "Pass123!"
}

###
GET https://localhost:5001/api/books?version=1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDFlOGE3My0zYjE2LTRhM2ItYmIzYS1jYzY5NzQyODE0NDciLCJlbWFpbCI6IndlYm1hc3RlcmRldmxpbkBnbWFpbC5jb20iLCJuYmYiOjE2MzE5NTA0ODcsImV4cCI6MTYzMjAzNjg4NywiaWF0IjoxNjMxOTUwNDg3fQ.AGifuElJBS1MeSy9tnI-CWkGD6Sr9guOHFFmHkMCyb0

###


GET https://localhost:5001/api/todos
Accept: application/json
version: 2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDFlOGE3My0zYjE2LTRhM2ItYmIzYS1jYzY5NzQyODE0NDciLCJlbWFpbCI6IndlYm1hc3RlcmRldmxpbkBnbWFpbC5jb20iLCJuYmYiOjE2MzE5NTA0ODcsImV4cCI6MTYzMjAzNjg4NywiaWF0IjoxNjMxOTUwNDg3fQ.AGifuElJBS1MeSy9tnI-CWkGD6Sr9guOHFFmHkMCyb0

###


