POST https://localhost:5001/api/users/auth
Content-Type: application/json

{
  "email": "webmasterdevlin@gmail.com",
  "password": "Pass123!"
}

###
GET https://localhost:5001/api/books?version=1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDFlOGE3My0zYjE2LTRhM2ItYmIzYS1jYzY5NzQyODE0NDciLCJlbWFpbCI6IndlYm1hc3RlcmRldmxpbkBnbWFpbC5jb20iLCJuYmYiOjE2MzM3MDE4NDQsImV4cCI6MTYzMzc4ODI0NCwiaWF0IjoxNjMzNzAxODQ0fQ.kO80HKIb-Xq5ejh921lMsw1_2bFlGcWo4yeiddiHM9E

###


GET https://localhost:5001/api/todos
Accept: application/json
version: 2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDFlOGE3My0zYjE2LTRhM2ItYmIzYS1jYzY5NzQyODE0NDciLCJlbWFpbCI6IndlYm1hc3RlcmRldmxpbkBnbWFpbC5jb20iLCJuYmYiOjE2MzM3MDE4NDQsImV4cCI6MTYzMzc4ODI0NCwiaWF0IjoxNjMzNzAxODQ0fQ.kO80HKIb-Xq5ejh921lMsw1_2bFlGcWo4yeiddiHM9E

###


