// <auto-generated />
using System;
using AspNetCoreRepositoryPattern.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreRepositoryPattern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211008141644_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreRepositoryPattern.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a560d8e6-ed98-42cf-8556-c5c12a553c8d"),
                            Author = "Marcel Proust",
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(630),
                            Description = "Swanns Way, the first part of A la recherche de temps perdu, Marcel Prousts seven-part cycle, was published in 1913.",
                            Title = "In Search of Lost Time"
                        },
                        new
                        {
                            Id = new Guid("9175edd8-6ee3-426f-83b6-9d3d90fd8116"),
                            Author = "James Joyce",
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(1100),
                            Description = "Ulysses chronicles the passage of Leopold Bloom through Dublin during an ordinary day, June 16, 1904.",
                            Title = "Ulysses"
                        },
                        new
                        {
                            Id = new Guid("457d57c6-8514-4d5c-b0b7-d72246df5dea"),
                            Author = "Miguel de Cervantes",
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(1110),
                            Description = "Alonso Quixano, a retired country gentleman in his fifties, lives in an unnamed section of La Mancha with his niece and a housekeeper.",
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = new Guid("3c1fd1eb-3ad3-4108-b236-b5275d140baa"),
                            Author = "Gabriel Garcia Marquez",
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(1120),
                            Description = "One of the 20th century's enduring works, One Hundred Years of Solitude is a widely beloved and acclaimed novel known throughout the world...",
                            Title = "One Hundred Years of Solitude"
                        });
                });

            modelBuilder.Entity("AspNetCoreRepositoryPattern.Models.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(54)
                        .HasColumnType("nvarchar(54)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(54)
                        .HasColumnType("nvarchar(54)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(54)
                        .HasColumnType("nvarchar(54)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8c8b904-d7ed-48bf-90d7-297e412e2320"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(4440),
                            DateOfBirth = new DateTime(2021, 10, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "jakoblarsen@gmail.com",
                            FirstName = "Jakob",
                            LastName = "Larsen",
                            Mobile = "90901234"
                        },
                        new
                        {
                            Id = new Guid("0826373d-c58d-4db3-957e-d83c7705a4b8"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(4880),
                            DateOfBirth = new DateTime(2021, 10, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "noraolsen@gmail.com",
                            FirstName = "Nora",
                            LastName = "Olsen",
                            Mobile = "90896745"
                        },
                        new
                        {
                            Id = new Guid("0a3ecdf5-4685-4eab-811f-a2545777030a"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(4890),
                            DateOfBirth = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(4890),
                            Email = "emiljohansen@gmail.com",
                            FirstName = "Emil",
                            LastName = "Johansen",
                            Mobile = "90452378"
                        },
                        new
                        {
                            Id = new Guid("1758c6df-5d92-4eff-a5c0-f65c40c01621"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 548, DateTimeKind.Local).AddTicks(4900),
                            DateOfBirth = new DateTime(2021, 10, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "emmahansen@gmail.com",
                            FirstName = "Emma",
                            LastName = "Hansen",
                            Mobile = "90129034"
                        });
                });

            modelBuilder.Entity("AspNetCoreRepositoryPattern.Models.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(54)
                        .HasColumnType("nvarchar(54)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7c222b7-7e82-4a01-8085-b5abc191f777"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 546, DateTimeKind.Local).AddTicks(5460),
                            Done = true,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("90d4e85a-54d8-48a9-b3a8-63d5560ea4bc"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 546, DateTimeKind.Local).AddTicks(6030),
                            Done = true,
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = new Guid("892ed1f0-52bc-455f-999a-c3be73790dfa"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 546, DateTimeKind.Local).AddTicks(6040),
                            Done = true,
                            Name = "Coding"
                        },
                        new
                        {
                            Id = new Guid("cfa7b2b2-08a0-4361-9dce-fe2dbe789190"),
                            CreatedAt = new DateTime(2021, 10, 8, 16, 16, 44, 546, DateTimeKind.Local).AddTicks(6050),
                            Done = true,
                            Name = "Travelling"
                        });
                });

            modelBuilder.Entity("AspNetCoreRepositoryPattern.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
